"""device biometric tracking

Revision ID: 30f7ae779042
Revises: 677485fc5d96
Create Date: 2026-07-16 12:40:56.392579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f7ae779042'
down_revision: Union[str, Sequence[str], None] = '677485fc5d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device_biometrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'has_biometrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_biometrics', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('user_device_biometrics')
    # ### end Alembic commands ###
