"""add_phone_number_to_profile

Revision ID: 882e08267b3d
Revises: ff8ba2d142a0
Create Date: 2026-07-12 13:24:12.858747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882e08267b3d'
down_revision: Union[str, Sequence[str], None] = 'ff8ba2d142a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'phone_number')
    # ### end Alembic commands ###
