"""Add medical options table

Revision ID: 89b398d0b329
Revises: 9c94fe7b2d91
Create Date: 2026-07-16 05:54:17.956908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b398d0b329'
down_revision: Union[str, Sequence[str], None] = '9c94fe7b2d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_options_category'), 'medical_options', ['category'], unique=False)
    op.create_index('ix_medical_options_category_status', 'medical_options', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_medical_options_created_by'), 'medical_options', ['created_by'], unique=False)
    op.create_index(op.f('ix_medical_options_slug'), 'medical_options', ['slug'], unique=False)
    op.create_index(op.f('ix_medical_options_uid'), 'medical_options', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_options_uid'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_slug'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_created_by'), table_name='medical_options')
    op.drop_index('ix_medical_options_category_status', table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_category'), table_name='medical_options')
    op.drop_table('medical_options')
    # ### end Alembic commands ###
