"""use_separate_catalog_and_single_selection_table

Revision ID: bd1e62c8968b
Revises: c177b938519f
Create Date: 2026-07-17 19:14:36.483892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd1e62c8968b'
down_revision: Union[str, Sequence[str], None] = 'c177b938519f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('allergy_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allergy_type', 'slug', name='uq_allergies_type_slug')
    )
    op.create_index(op.f('ix_allergies_created_by'), 'allergies', ['created_by'], unique=False)
    op.create_index(op.f('ix_allergies_slug'), 'allergies', ['slug'], unique=False)
    op.create_index(op.f('ix_allergies_uid'), 'allergies', ['uid'], unique=True)
    op.create_table('family_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_family_histories_slug')
    )
    op.create_index(op.f('ix_family_histories_created_by'), 'family_histories', ['created_by'], unique=False)
    op.create_index(op.f('ix_family_histories_slug'), 'family_histories', ['slug'], unique=False)
    op.create_index(op.f('ix_family_histories_uid'), 'family_histories', ['uid'], unique=True)
    op.create_table('medical_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_type', 'slug', name='uq_conditions_type_slug')
    )
    op.create_index(op.f('ix_medical_conditions_created_by'), 'medical_conditions', ['created_by'], unique=False)
    op.create_index(op.f('ix_medical_conditions_slug'), 'medical_conditions', ['slug'], unique=False)
    op.create_index(op.f('ix_medical_conditions_uid'), 'medical_conditions', ['uid'], unique=True)
    op.create_table('profile_medical_selections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('item_uid', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_medical_selections_category'), 'profile_medical_selections', ['category'], unique=False)
    op.create_index(op.f('ix_profile_medical_selections_item_uid'), 'profile_medical_selections', ['item_uid'], unique=False)
    op.create_index(op.f('ix_profile_medical_selections_profile_id'), 'profile_medical_selections', ['profile_id'], unique=False)

    # ─── DATA MIGRATION ─────────────────────────────
    bind = op.get_bind()

    # 1. Fetch all options from 'medical_options'
    res_options = bind.execute(sa.text("SELECT id, uid, category, slug, display_name, created_by, status, created_at, updated_at FROM medical_options")).fetchall()
    
    # Maps old medical_option ID -> catalog UID
    option_id_to_uid = {}
    for r in res_options:
        opt_id, opt_uid, opt_category, opt_slug, opt_display, opt_created_by, opt_status, opt_created_at, opt_updated_at = r
        option_id_to_uid[opt_id] = opt_uid
        
        # Determine target table
        if opt_category.endswith("_allergy"):
            allergy_type = opt_category.split("_")[0]
            bind.execute(
                sa.text(
                    "INSERT INTO allergies (uid, allergy_type, slug, display_name, created_by, status, created_at, updated_at) "
                    "VALUES (:uid, :allergy_type, :slug, :display_name, :created_by, :status, :created_at, :updated_at) "
                    "ON CONFLICT (allergy_type, slug) DO NOTHING"
                ),
                {
                    "uid": opt_uid,
                    "allergy_type": allergy_type,
                    "slug": opt_slug,
                    "display_name": opt_display,
                    "created_by": opt_created_by,
                    "status": opt_status,
                    "created_at": opt_created_at,
                    "updated_at": opt_updated_at
                }
            )
        elif opt_category in ["chronic_condition", "syndrome"]:
            condition_type = "chronic" if opt_category == "chronic_condition" else "syndrome"
            bind.execute(
                sa.text(
                    "INSERT INTO medical_conditions (uid, condition_type, slug, display_name, created_by, status, created_at, updated_at) "
                    "VALUES (:uid, :condition_type, :slug, :display_name, :created_by, :status, :created_at, :updated_at) "
                    "ON CONFLICT (condition_type, slug) DO NOTHING"
                ),
                {
                    "uid": opt_uid,
                    "condition_type": condition_type,
                    "slug": opt_slug,
                    "display_name": opt_display,
                    "created_by": opt_created_by,
                    "status": opt_status,
                    "created_at": opt_created_at,
                    "updated_at": opt_updated_at
                }
            )
        elif opt_category == "family_history":
            bind.execute(
                sa.text(
                    "INSERT INTO family_histories (uid, slug, display_name, created_by, status, created_at, updated_at) "
                    "VALUES (:uid, :slug, :display_name, :created_by, :status, :created_at, :updated_at) "
                    "ON CONFLICT (slug) DO NOTHING"
                ),
                {
                    "uid": opt_uid,
                    "slug": opt_slug,
                    "display_name": opt_display,
                    "created_by": opt_created_by,
                    "status": opt_status,
                    "created_at": opt_created_at,
                    "updated_at": opt_updated_at
                }
            )

    # 2. Fetch all profile selections from 'profile_medical_options'
    res_selections = bind.execute(sa.text("SELECT profile_id, medical_option_id, duration, created_at FROM profile_medical_options")).fetchall()
    for s in res_selections:
        profile_id, old_opt_id, duration, created_at = s
        item_uid = option_id_to_uid.get(old_opt_id)
        if not item_uid:
            continue
            
        # Get category of the old option
        opt_category = next((r[2] for r in res_options if r[0] == old_opt_id), None)
        if not opt_category:
            continue
            
        bind.execute(
            sa.text(
                "INSERT INTO profile_medical_selections (profile_id, item_uid, category, duration, created_at) "
                "VALUES (:profile_id, :item_uid, :category, :duration, :created_at)"
            ),
            {
                "profile_id": profile_id,
                "item_uid": item_uid,
                "category": opt_category,
                "duration": duration,
                "created_at": created_at
            }
        )

    op.drop_index(op.f('ix_profile_medical_options_created_by'), table_name='profile_medical_options')
    op.drop_index(op.f('ix_profile_medical_options_medical_option_id'), table_name='profile_medical_options')
    op.drop_index(op.f('ix_profile_medical_options_profile_id'), table_name='profile_medical_options')
    op.drop_table('profile_medical_options')
    op.drop_index(op.f('ix_medical_options_category'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_created_by'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_slug'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_uid'), table_name='medical_options')
    op.drop_table('medical_options')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('medical_options_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_options_pkey')),
    sa.UniqueConstraint('category', 'slug', name=op.f('uq_medical_options_category_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_medical_options_uid'), 'medical_options', ['uid'], unique=True)
    op.create_index(op.f('ix_medical_options_slug'), 'medical_options', ['slug'], unique=False)
    op.create_index(op.f('ix_medical_options_created_by'), 'medical_options', ['created_by'], unique=False)
    op.create_index(op.f('ix_medical_options_category'), 'medical_options', ['category'], unique=False)
    op.create_table('profile_medical_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medical_option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('profile_medical_options_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medical_option_id'], ['medical_options.id'], name=op.f('profile_medical_options_medical_option_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_medical_options_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_medical_options_pkey'))
    )
    op.create_index(op.f('ix_profile_medical_options_profile_id'), 'profile_medical_options', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_medical_options_medical_option_id'), 'profile_medical_options', ['medical_option_id'], unique=False)
    op.create_index(op.f('ix_profile_medical_options_created_by'), 'profile_medical_options', ['created_by'], unique=False)
    op.drop_index(op.f('ix_profile_medical_selections_profile_id'), table_name='profile_medical_selections')
    op.drop_index(op.f('ix_profile_medical_selections_item_uid'), table_name='profile_medical_selections')
    op.drop_index(op.f('ix_profile_medical_selections_category'), table_name='profile_medical_selections')
    op.drop_table('profile_medical_selections')
    op.drop_index(op.f('ix_medical_conditions_uid'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_slug'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_created_by'), table_name='medical_conditions')
    op.drop_table('medical_conditions')
    op.drop_index(op.f('ix_family_histories_uid'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_slug'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_created_by'), table_name='family_histories')
    op.drop_table('family_histories')
    op.drop_index(op.f('ix_allergies_uid'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_slug'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_created_by'), table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###
