"""use_single_medical_options_table

Revision ID: c177b938519f
Revises: d5dadae8c8b5
Create Date: 2026-07-17 18:40:26.779653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c177b938519f'
down_revision: Union[str, Sequence[str], None] = 'd5dadae8c8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'slug', name='uq_medical_options_category_slug')
    )
    op.create_index(op.f('ix_medical_options_category'), 'medical_options', ['category'], unique=False)
    op.create_index(op.f('ix_medical_options_created_by'), 'medical_options', ['created_by'], unique=False)
    op.create_index(op.f('ix_medical_options_slug'), 'medical_options', ['slug'], unique=False)
    op.create_index(op.f('ix_medical_options_uid'), 'medical_options', ['uid'], unique=True)
    op.create_table('profile_medical_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('medical_option_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medical_option_id'], ['medical_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_medical_options_created_by'), 'profile_medical_options', ['created_by'], unique=False)
    op.create_index(op.f('ix_profile_medical_options_medical_option_id'), 'profile_medical_options', ['medical_option_id'], unique=False)
    op.create_index(op.f('ix_profile_medical_options_profile_id'), 'profile_medical_options', ['profile_id'], unique=False)

    # ─── DATA MIGRATION AND DEDUPLICATION ─────────────────────────────
    bind = op.get_bind()
    
    # 1. Migrate allergies
    res_allergies = bind.execute(sa.text("SELECT id, uid, allergy_type, slug, display_name, created_by, status, created_at, updated_at FROM allergies")).fetchall()
    allergy_id_map = {}
    for r in res_allergies:
        category = f"{r[2]}_allergy"
        exists = bind.execute(
            sa.text("SELECT id FROM medical_options WHERE category = :category AND slug = :slug"),
            {"category": category, "slug": r[3]}
        ).fetchone()
        
        if exists:
            new_id = exists[0]
        else:
            insert_res = bind.execute(
                sa.text(
                    "INSERT INTO medical_options (uid, category, slug, display_name, created_by, status, created_at, updated_at) "
                    "VALUES (:uid, :category, :slug, :display_name, :created_by, :status, :created_at, :updated_at) RETURNING id"
                ),
                {
                    "uid": r[1],
                    "category": category,
                    "slug": r[3],
                    "display_name": r[4],
                    "created_by": r[5],
                    "status": r[6],
                    "created_at": r[7],
                    "updated_at": r[8]
                }
            )
            new_id = insert_res.fetchone()[0]
        allergy_id_map[r[0]] = new_id

    # 2. Migrate medical_conditions
    res_conditions = bind.execute(sa.text("SELECT id, uid, condition_type, slug, display_name, created_by, status, created_at, updated_at FROM medical_conditions")).fetchall()
    condition_id_map = {}
    for r in res_conditions:
        category = "chronic_condition" if r[2] == "chronic" else "syndrome"
        exists = bind.execute(
            sa.text("SELECT id FROM medical_options WHERE category = :category AND slug = :slug"),
            {"category": category, "slug": r[3]}
        ).fetchone()
        
        if exists:
            new_id = exists[0]
        else:
            insert_res = bind.execute(
                sa.text(
                    "INSERT INTO medical_options (uid, category, slug, display_name, created_by, status, created_at, updated_at) "
                    "VALUES (:uid, :category, :slug, :display_name, :created_by, :status, :created_at, :updated_at) RETURNING id"
                ),
                {
                    "uid": r[1],
                    "category": category,
                    "slug": r[3],
                    "display_name": r[4],
                    "created_by": r[5],
                    "status": r[6],
                    "created_at": r[7],
                    "updated_at": r[8]
                }
            )
            new_id = insert_res.fetchone()[0]
        condition_id_map[r[0]] = new_id

    # 3. Migrate family_histories
    res_histories = bind.execute(sa.text("SELECT id, uid, slug, display_name, created_by, status, created_at, updated_at FROM family_histories")).fetchall()
    history_id_map = {}
    for r in res_histories:
        category = "family_history"
        exists = bind.execute(
            sa.text("SELECT id FROM medical_options WHERE category = :category AND slug = :slug"),
            {"category": category, "slug": r[2]}
        ).fetchone()
        
        if exists:
            new_id = exists[0]
        else:
            insert_res = bind.execute(
                sa.text(
                    "INSERT INTO medical_options (uid, category, slug, display_name, created_by, status, created_at, updated_at) "
                    "VALUES (:uid, :category, :slug, :display_name, :created_by, :status, :created_at, :updated_at) RETURNING id"
                ),
                {
                    "uid": r[1],
                    "category": category,
                    "slug": r[2],
                    "display_name": r[3],
                    "created_by": r[4],
                    "status": r[5],
                    "created_at": r[6],
                    "updated_at": r[7]
                }
            )
            new_id = insert_res.fetchone()[0]
        history_id_map[r[0]] = new_id

    # 4. Migrate junction table: profile_allergies -> profile_medical_options
    res_prof_allergies = bind.execute(sa.text("SELECT profile_id, allergy_id, created_by, created_at FROM profile_allergies")).fetchall()
    for r in res_prof_allergies:
        new_option_id = allergy_id_map.get(r[1])
        if new_option_id:
            bind.execute(
                sa.text(
                    "INSERT INTO profile_medical_options (profile_id, medical_option_id, duration, created_by, created_at) "
                    "VALUES (:profile_id, :medical_option_id, NULL, :created_by, :created_at)"
                ),
                {
                    "profile_id": r[0],
                    "medical_option_id": new_option_id,
                    "created_by": r[2],
                    "created_at": r[3]
                }
            )

    # 5. Migrate junction table: profile_conditions -> profile_medical_options
    res_prof_conditions = bind.execute(sa.text("SELECT profile_id, condition_id, duration, created_by, created_at FROM profile_conditions")).fetchall()
    for r in res_prof_conditions:
        new_option_id = condition_id_map.get(r[1])
        if new_option_id:
            bind.execute(
                sa.text(
                    "INSERT INTO profile_medical_options (profile_id, medical_option_id, duration, created_by, created_at) "
                    "VALUES (:profile_id, :medical_option_id, :duration, :created_by, :created_at)"
                ),
                {
                    "profile_id": r[0],
                    "medical_option_id": new_option_id,
                    "duration": r[2],
                    "created_by": r[3],
                    "created_at": r[4]
                }
            )

    # 6. Migrate junction table: profile_family_histories -> profile_medical_options
    res_prof_histories = bind.execute(sa.text("SELECT profile_id, family_history_id, created_by, created_at FROM profile_family_histories")).fetchall()
    for r in res_prof_histories:
        new_option_id = history_id_map.get(r[1])
        if new_option_id:
            bind.execute(
                sa.text(
                    "INSERT INTO profile_medical_options (profile_id, medical_option_id, duration, created_by, created_at) "
                    "VALUES (:profile_id, :medical_option_id, NULL, :created_by, :created_at)"
                ),
                {
                    "profile_id": r[0],
                    "medical_option_id": new_option_id,
                    "created_by": r[2],
                    "created_at": r[3]
                }
            )

    # Drop junction tables first
    op.drop_index(op.f('ix_profile_family_histories_created_by'), table_name='profile_family_histories')
    op.drop_index(op.f('ix_profile_family_histories_family_history_id'), table_name='profile_family_histories')
    op.drop_index(op.f('ix_profile_family_histories_profile_id'), table_name='profile_family_histories')
    op.drop_table('profile_family_histories')
    
    op.drop_index(op.f('ix_profile_allergies_allergy_id'), table_name='profile_allergies')
    op.drop_index(op.f('ix_profile_allergies_created_by'), table_name='profile_allergies')
    op.drop_index(op.f('ix_profile_allergies_profile_id'), table_name='profile_allergies')
    op.drop_table('profile_allergies')
    
    op.drop_index(op.f('ix_profile_conditions_condition_id'), table_name='profile_conditions')
    op.drop_index(op.f('ix_profile_conditions_created_by'), table_name='profile_conditions')
    op.drop_index(op.f('ix_profile_conditions_profile_id'), table_name='profile_conditions')
    op.drop_table('profile_conditions')

    # Drop catalog tables second
    op.drop_index(op.f('ix_allergies_created_by'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_slug'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_uid'), table_name='allergies')
    op.drop_table('allergies')
    
    op.drop_index(op.f('ix_family_histories_created_by'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_slug'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_uid'), table_name='family_histories')
    op.drop_table('family_histories')
    
    op.drop_index(op.f('ix_medical_conditions_created_by'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_slug'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_uid'), table_name='medical_conditions')
    op.drop_table('medical_conditions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['medical_conditions.id'], name=op.f('profile_conditions_condition_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('profile_conditions_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_conditions_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_conditions_pkey'))
    )
    op.create_index(op.f('ix_profile_conditions_profile_id'), 'profile_conditions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_conditions_created_by'), 'profile_conditions', ['created_by'], unique=False)
    op.create_index(op.f('ix_profile_conditions_condition_id'), 'profile_conditions', ['condition_id'], unique=False)
    op.create_table('medical_conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('condition_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('medical_conditions_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_conditions_pkey'))
    )
    op.create_index(op.f('ix_medical_conditions_uid'), 'medical_conditions', ['uid'], unique=True)
    op.create_index(op.f('ix_medical_conditions_slug'), 'medical_conditions', ['slug'], unique=False)
    op.create_index(op.f('ix_medical_conditions_created_by'), 'medical_conditions', ['created_by'], unique=False)
    op.create_table('family_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('family_histories_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('family_histories_pkey'))
    )
    op.create_index(op.f('ix_family_histories_uid'), 'family_histories', ['uid'], unique=True)
    op.create_index(op.f('ix_family_histories_slug'), 'family_histories', ['slug'], unique=False)
    op.create_index(op.f('ix_family_histories_created_by'), 'family_histories', ['created_by'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('allergy_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('allergies_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('allergies_pkey'))
    )
    op.create_index(op.f('ix_allergies_uid'), 'allergies', ['uid'], unique=True)
    op.create_index(op.f('ix_allergies_slug'), 'allergies', ['slug'], unique=False)
    op.create_index(op.f('ix_allergies_created_by'), 'allergies', ['created_by'], unique=False)
    op.create_table('profile_allergies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allergy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['allergy_id'], ['allergies.id'], name=op.f('profile_allergies_allergy_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('profile_allergies_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_allergies_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_allergies_pkey'))
    )
    op.create_index(op.f('ix_profile_allergies_profile_id'), 'profile_allergies', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_allergies_created_by'), 'profile_allergies', ['created_by'], unique=False)
    op.create_index(op.f('ix_profile_allergies_allergy_id'), 'profile_allergies', ['allergy_id'], unique=False)
    op.create_table('profile_family_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('family_history_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('profile_family_histories_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_history_id'], ['family_histories.id'], name=op.f('profile_family_histories_family_history_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_family_histories_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_family_histories_pkey'))
    )
    op.create_index(op.f('ix_profile_family_histories_profile_id'), 'profile_family_histories', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_family_histories_family_history_id'), 'profile_family_histories', ['family_history_id'], unique=False)
    op.create_index(op.f('ix_profile_family_histories_created_by'), 'profile_family_histories', ['created_by'], unique=False)
    op.drop_index(op.f('ix_profile_medical_options_profile_id'), table_name='profile_medical_options')
    op.drop_index(op.f('ix_profile_medical_options_medical_option_id'), table_name='profile_medical_options')
    op.drop_index(op.f('ix_profile_medical_options_created_by'), table_name='profile_medical_options')
    op.drop_table('profile_medical_options')
    op.drop_index(op.f('ix_medical_options_uid'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_slug'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_created_by'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_category'), table_name='medical_options')
    op.drop_table('medical_options')
    # ### end Alembic commands ###
