"""expand_medications_table

Revision ID: c5a1c8662497
Revises: 89b398d0b329
Create Date: 2026-07-16 07:22:23.705943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a1c8662497'
down_revision: Union[str, Sequence[str], None] = '89b398d0b329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('slug', sa.String(length=150), nullable=True))
    op.add_column('medications', sa.Column('timings', sa.JSON(), nullable=True))
    op.add_column('medications', sa.Column('instructions', sa.String(length=255), nullable=True))
    op.add_column('medications', sa.Column('food_relation', sa.String(length=100), nullable=True))
    op.add_column('medications', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'tags')
    op.drop_column('medications', 'food_relation')
    op.drop_column('medications', 'instructions')
    op.drop_column('medications', 'timings')
    op.drop_column('medications', 'slug')
    # ### end Alembic commands ###
