"""normalize_health_profile_junction_tables

Revision ID: d5dadae8c8b5
Revises: f136381ceb5f
Create Date: 2026-07-17 17:53:17.626933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dadae8c8b5'
down_revision: Union[str, Sequence[str], None] = 'f136381ceb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_allergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('allergy_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allergy_id'], ['allergies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_allergies_allergy_id'), 'profile_allergies', ['allergy_id'], unique=False)
    op.create_index(op.f('ix_profile_allergies_created_by'), 'profile_allergies', ['created_by'], unique=False)
    op.create_index(op.f('ix_profile_allergies_profile_id'), 'profile_allergies', ['profile_id'], unique=False)
    op.create_table('profile_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['medical_conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_conditions_condition_id'), 'profile_conditions', ['condition_id'], unique=False)
    op.create_index(op.f('ix_profile_conditions_created_by'), 'profile_conditions', ['created_by'], unique=False)
    op.create_index(op.f('ix_profile_conditions_profile_id'), 'profile_conditions', ['profile_id'], unique=False)
    op.create_table('profile_family_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('family_history_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_history_id'], ['family_histories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_family_histories_created_by'), 'profile_family_histories', ['created_by'], unique=False)
    op.create_index(op.f('ix_profile_family_histories_family_history_id'), 'profile_family_histories', ['family_history_id'], unique=False)
    op.create_index(op.f('ix_profile_family_histories_profile_id'), 'profile_family_histories', ['profile_id'], unique=False)
    
    # ─── DATA MIGRATION AND DEDUPLICATION ─────────────────────────────
    bind = op.get_bind()
    
    # 1. Migrate Allergies
    res_allergies = bind.execute(sa.text("SELECT id, profile_id, allergy_type, slug, display_name, created_by FROM allergies")).fetchall()
    allergy_catalog_map = {}
    # Pass 1: Seeded items (where profile_id is NULL)
    for r in res_allergies:
        if r[1] is None:
            allergy_catalog_map[(r[3], r[2])] = r[0] # (slug, allergy_type) -> id
            
    # Pass 2: User-created unique items
    for r in res_allergies:
        if r[1] is not None:
            key = (r[3], r[2])
            if key not in allergy_catalog_map:
                allergy_catalog_map[key] = r[0]
                
    # Pass 3: Insert junctions
    for r in res_allergies:
        profile_id = r[1]
        if profile_id is not None:
            key = (r[3], r[2])
            catalog_id = allergy_catalog_map[key]
            created_by = r[5]
            bind.execute(
                sa.text(
                    "INSERT INTO profile_allergies (profile_id, allergy_id, created_by, created_at) "
                    "VALUES (:profile_id, :allergy_id, :created_by, NOW())"
                ),
                {"profile_id": profile_id, "allergy_id": catalog_id, "created_by": created_by}
            )
            
    # Pass 4: Delete duplicates in catalog
    allergy_master_ids = set(allergy_catalog_map.values())
    if allergy_master_ids:
        bind.execute(
            sa.text("DELETE FROM allergies WHERE id NOT IN :master_ids"),
            {"master_ids": tuple(allergy_master_ids)}
        )

    # 2. Migrate Medical Conditions
    res_conditions = bind.execute(sa.text("SELECT id, profile_id, condition_type, slug, display_name, created_by, duration FROM medical_conditions")).fetchall()
    condition_catalog_map = {}
    for r in res_conditions:
        if r[1] is None:
            condition_catalog_map[(r[3], r[2])] = r[0]
            
    for r in res_conditions:
        if r[1] is not None:
            key = (r[3], r[2])
            if key not in condition_catalog_map:
                condition_catalog_map[key] = r[0]
                
    for r in res_conditions:
        profile_id = r[1]
        if profile_id is not None:
            key = (r[3], r[2])
            catalog_id = condition_catalog_map[key]
            created_by = r[5]
            duration = r[6]
            bind.execute(
                sa.text(
                    "INSERT INTO profile_conditions (profile_id, condition_id, duration, created_by, created_at) "
                    "VALUES (:profile_id, :condition_id, :duration, :created_by, NOW())"
                ),
                {"profile_id": profile_id, "condition_id": catalog_id, "duration": duration, "created_by": created_by}
            )
            
    condition_master_ids = set(condition_catalog_map.values())
    if condition_master_ids:
        bind.execute(
            sa.text("DELETE FROM medical_conditions WHERE id NOT IN :master_ids"),
            {"master_ids": tuple(condition_master_ids)}
        )

    # 3. Migrate Family Histories
    res_histories = bind.execute(sa.text("SELECT id, profile_id, slug, display_name, created_by FROM family_histories")).fetchall()
    history_catalog_map = {}
    for r in res_histories:
        if r[1] is None:
            history_catalog_map[r[2]] = r[0]
            
    for r in res_histories:
        if r[1] is not None:
            key = r[2]
            if key not in history_catalog_map:
                history_catalog_map[key] = r[0]
                
    for r in res_histories:
        profile_id = r[1]
        if profile_id is not None:
            key = r[2]
            catalog_id = history_catalog_map[key]
            created_by = r[4]
            bind.execute(
                sa.text(
                    "INSERT INTO profile_family_histories (profile_id, family_history_id, created_by, created_at) "
                    "VALUES (:profile_id, :family_history_id, :created_by, NOW())"
                ),
                {"profile_id": profile_id, "family_history_id": catalog_id, "created_by": created_by}
            )
            
    history_master_ids = set(history_catalog_map.values())
    if history_master_ids:
        bind.execute(
            sa.text("DELETE FROM family_histories WHERE id NOT IN :master_ids"),
            {"master_ids": tuple(history_master_ids)}
        )

    # ─── SCHEMA UPGRADES (DROP COLUMNS) ────────────────────────────────
    op.drop_index(op.f('ix_allergies_profile_id'), table_name='allergies')
    op.drop_constraint(op.f('allergies_profile_id_fkey'), 'allergies', type_='foreignkey')
    op.drop_column('allergies', 'profile_id')
    op.drop_index(op.f('ix_family_histories_profile_id'), table_name='family_histories')
    op.drop_constraint(op.f('family_histories_profile_id_fkey'), 'family_histories', type_='foreignkey')
    op.drop_column('family_histories', 'profile_id')
    op.drop_index(op.f('ix_medical_conditions_profile_id'), table_name='medical_conditions')
    op.drop_constraint(op.f('medical_conditions_profile_id_fkey'), 'medical_conditions', type_='foreignkey')
    op.drop_column('medical_conditions', 'profile_id')
    op.drop_column('medical_conditions', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_conditions', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('medical_conditions', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('medical_conditions_profile_id_fkey'), 'medical_conditions', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_medical_conditions_profile_id'), 'medical_conditions', ['profile_id'], unique=False)
    op.add_column('family_histories', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('family_histories_profile_id_fkey'), 'family_histories', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_family_histories_profile_id'), 'family_histories', ['profile_id'], unique=False)
    op.add_column('allergies', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('allergies_profile_id_fkey'), 'allergies', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_allergies_profile_id'), 'allergies', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_profile_family_histories_profile_id'), table_name='profile_family_histories')
    op.drop_index(op.f('ix_profile_family_histories_family_history_id'), table_name='profile_family_histories')
    op.drop_index(op.f('ix_profile_family_histories_created_by'), table_name='profile_family_histories')
    op.drop_table('profile_family_histories')
    op.drop_index(op.f('ix_profile_conditions_profile_id'), table_name='profile_conditions')
    op.drop_index(op.f('ix_profile_conditions_created_by'), table_name='profile_conditions')
    op.drop_index(op.f('ix_profile_conditions_condition_id'), table_name='profile_conditions')
    op.drop_table('profile_conditions')
    op.drop_index(op.f('ix_profile_allergies_profile_id'), table_name='profile_allergies')
    op.drop_index(op.f('ix_profile_allergies_created_by'), table_name='profile_allergies')
    op.drop_index(op.f('ix_profile_allergies_allergy_id'), table_name='profile_allergies')
    op.drop_table('profile_allergies')
    # ### end Alembic commands ###
