"""add_avatar_to_profile

Revision ID: d69fa67a6bb9
Revises: c8d0ee6a1c1e
Create Date: 2026-07-12 12:22:57.660554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69fa67a6bb9'
down_revision: Union[str, Sequence[str], None] = 'c8d0ee6a1c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar')
    # ### end Alembic commands ###
