"""remove medical options table and add properties to respective tables

Revision ID: f136381ceb5f
Revises: 30f7ae779042
Create Date: 2026-07-16 12:52:29.069484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f136381ceb5f'
down_revision: Union[str, Sequence[str], None] = '30f7ae779042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_options_category'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_category_status'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_created_by'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_slug'), table_name='medical_options')
    op.drop_index(op.f('ix_medical_options_uid'), table_name='medical_options')
    op.drop_table('medical_options')
    op.add_column('allergies', sa.Column('uid', sa.String(length=36), nullable=False))
    op.add_column('allergies', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('allergies', sa.Column('display_name', sa.String(length=255), nullable=False))
    op.add_column('allergies', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('allergies', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('allergies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('allergies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('allergies', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_allergies_created_by'), 'allergies', ['created_by'], unique=False)
    op.create_index(op.f('ix_allergies_slug'), 'allergies', ['slug'], unique=False)
    op.create_index(op.f('ix_allergies_uid'), 'allergies', ['uid'], unique=True)
    op.create_foreign_key(None, 'allergies', 'users', ['created_by'], ['uid'], ondelete='SET NULL')
    op.drop_column('allergies', 'name')
    op.add_column('family_histories', sa.Column('uid', sa.String(length=36), nullable=False))
    op.add_column('family_histories', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('family_histories', sa.Column('display_name', sa.String(length=255), nullable=False))
    op.add_column('family_histories', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('family_histories', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('family_histories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('family_histories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('family_histories', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_family_histories_created_by'), 'family_histories', ['created_by'], unique=False)
    op.create_index(op.f('ix_family_histories_slug'), 'family_histories', ['slug'], unique=False)
    op.create_index(op.f('ix_family_histories_uid'), 'family_histories', ['uid'], unique=True)
    op.create_foreign_key(None, 'family_histories', 'users', ['created_by'], ['uid'], ondelete='SET NULL')
    op.drop_column('family_histories', 'name')
    op.add_column('medical_conditions', sa.Column('uid', sa.String(length=36), nullable=False))
    op.add_column('medical_conditions', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('medical_conditions', sa.Column('display_name', sa.String(length=255), nullable=False))
    op.add_column('medical_conditions', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('medical_conditions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('medical_conditions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medical_conditions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('medical_conditions', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_medical_conditions_created_by'), 'medical_conditions', ['created_by'], unique=False)
    op.create_index(op.f('ix_medical_conditions_slug'), 'medical_conditions', ['slug'], unique=False)
    op.create_index(op.f('ix_medical_conditions_uid'), 'medical_conditions', ['uid'], unique=True)
    op.create_foreign_key(None, 'medical_conditions', 'users', ['created_by'], ['uid'], ondelete='SET NULL')
    op.drop_column('medical_conditions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_conditions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'medical_conditions', type_='foreignkey')
    op.drop_index(op.f('ix_medical_conditions_uid'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_slug'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_created_by'), table_name='medical_conditions')
    op.alter_column('medical_conditions', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('medical_conditions', 'updated_at')
    op.drop_column('medical_conditions', 'created_at')
    op.drop_column('medical_conditions', 'status')
    op.drop_column('medical_conditions', 'created_by')
    op.drop_column('medical_conditions', 'display_name')
    op.drop_column('medical_conditions', 'slug')
    op.drop_column('medical_conditions', 'uid')
    op.add_column('family_histories', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'family_histories', type_='foreignkey')
    op.drop_index(op.f('ix_family_histories_uid'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_slug'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_created_by'), table_name='family_histories')
    op.alter_column('family_histories', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('family_histories', 'updated_at')
    op.drop_column('family_histories', 'created_at')
    op.drop_column('family_histories', 'status')
    op.drop_column('family_histories', 'created_by')
    op.drop_column('family_histories', 'display_name')
    op.drop_column('family_histories', 'slug')
    op.drop_column('family_histories', 'uid')
    op.add_column('allergies', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'allergies', type_='foreignkey')
    op.drop_index(op.f('ix_allergies_uid'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_slug'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_created_by'), table_name='allergies')
    op.alter_column('allergies', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('allergies', 'updated_at')
    op.drop_column('allergies', 'created_at')
    op.drop_column('allergies', 'status')
    op.drop_column('allergies', 'created_by')
    op.drop_column('allergies', 'display_name')
    op.drop_column('allergies', 'slug')
    op.drop_column('allergies', 'uid')
    op.create_table('medical_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], name=op.f('medical_options_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_options_pkey'))
    )
    op.create_index(op.f('ix_medical_options_uid'), 'medical_options', ['uid'], unique=True)
    op.create_index(op.f('ix_medical_options_slug'), 'medical_options', ['slug'], unique=False)
    op.create_index(op.f('ix_medical_options_created_by'), 'medical_options', ['created_by'], unique=False)
    op.create_index(op.f('ix_medical_options_category_status'), 'medical_options', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_medical_options_category'), 'medical_options', ['category'], unique=False)
    # ### end Alembic commands ###
